### ISSUE TITLE
Permissions for models

### ISSUE THREAD

**Issue by evanoconnor** [SNEWS2/snewpy#1]
We need to be careful about posting models here. 

For models that are already publicly available, this is less of an issue, however, I'm sure some of the authors would like to sign off on (at least be notified of) us including their models here. 

Some of these models are not publicly available, in that case, please do not post these unless you have explicit permission to post them here (and state that in the README file).  This is not done for all of the models currently here.

In all cases, if adding models please include the necessary references for the data. This is not done for all of the models currently here.

**Comment by JostMigenda** [comment]
Follow-up discussed in #23.
