### ISSUE TITLE
Digits removed when collating files

### ISSUE THREAD

**Issue by soso128** [SNEWS2/snewpy#122]
Dear All,

I have installed the following commit of snewpy: 7ac532a4f4cd6723e53e3f41ed023ed542f63373 and modified python/snewpy/scripts/TimeSeries.py to keep all the generated files, using:

snowglobes.collate(SNOwGLoBES_path, outfile, detector_input="icecube", skip_plots=True, remove_generated_files = False)

When I compare the collated files to the original files, I find that, for a few rate values and for some files, the first digit of the result has been removed. See for example the IBD rate for E = 0.002739 GeV in:

nakazato-LS220-BH-z0.004-s30.0.tbin9.AdiabaticMSW_NMO.-0.110,0.342,30-10.0kpc_ibd_icecube_events_smeared_unweighted.dat  (rate = 3.65327e-05)

compared to

Collated_nakazato-LS220-BH-z0.004-s30.0.tbin9.AdiabaticMSW_NMO.-0.110,0.342,30-10.0kpc_icecube_events_smeared_unweighted.dat (rate = 6.5327e-06)

Best regards,
Sonia

**Comment by soso128** [comment]
Hi Jost, I confirm that it works with your patch. Thanks a lot!

**Comment by JostMigenda** [comment]
Excellent, thanks for checking! 🎉
