### ISSUE TITLE
Caching the dependencies for CI jobs

### ISSUE THREAD

**Issue by Sheshuk** [SNEWS2/snewpy#137]
We are installing GLOBES and SNOWGLOBES for each integration test job. 
It's possible to use [caching action](https://docs.github.com/en/actions/advanced-guides/caching-dependencies-to-speed-up-workflows) to keep the directories. 
Another solution is to prepare a Docker container and use it to run the jobs, using [jobs.<job-id>.container](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idcontainer) option

**Comment by JostMigenda** [comment]
With #193 merged, we don’t depend on GLoBES anymore; and even SNOwGLoBES only needs to be downloaded, not compiled; so caching them wouldn’t offer a notable performance benefit anymore.

Do you think it’s worth keeping this issue open for caching pip dependencies, or can we close this?

**Comment by Sheshuk** [comment]
Agreed!
