### ISSUE TITLE
Units in astropy.table.Table columns

### ISSUE THREAD

**Issue by nuberoi** [SNEWS2/snewpy#14]
The columns of the `astropy` tables contained in the ASTERIA fits files (such as those in `models/Nakazato_2013`) have units in the metadata, but the individual elements in the columns are dimensionless. For instance, `time = model.get_time()` returns an array with units seconds, but `time[0]` is dimensionless. This means that the units are lost while iterating over all time bins.

**Comment by JostMigenda** [comment]
Trying this with the current version of the code:
```
>>> from snewpy.models import Nakazato_2013
WARNING:root:No module named 'photospline'
>>> model = Nakazato_2013('models/Nakazato_2013/nakazato-shen-z0.02-t_rev100ms-s20.0.fits')
>>> model.get_time()[0]
<Quantity -0.05 s>
```
It seems this was fixed some time in the last 16 months (as far as I can tell, the only exception is the `Janka` model—see my remark in #45), so I’ll close this issue.
