### ISSUE TITLE
Presupernova models implementation

### ISSUE THREAD

**Issue by Sheshuk** [SNEWS2/snewpy#140]
A top-level issue for coordinating effort on implementing simulation of presupernova models, getting the event numbers vs. time vs. Energy in the detectors.

- [x] #121   
- [x] #141
- [x] #142
- [ ] #143

**Comment by JostMigenda** [comment]
It looks like there’s no more coordination needed on this. To avoid having two issues open for the one remaining task, let’s close this one and keep #143 open.
