### ISSUE TITLE
GLoBES install version numbers in readme

### ISSUE THREAD

**Issue by PeterDenton** [SNEWS2/snewpy#146]
In the readme there is a brief sketch on how to install GLoBES. I'm not sure if you only plan on interfacing with v3.2.17, but if newer version every come out (in fact they are up to 3.2.18 now) you may want to have a way to download the latest version. In any case, in the example you switch between 3.2.17 and 3.2.16.

**Comment by JostMigenda** [comment]
I’ve just merged PR #112 that fixes the typo regarding 3.2.16 (and includes a few more updates to the README file). Thanks for the reminder!

With GLoBES 3.2.18, @schol mentioned that some SNOwGLoBES users had encountered problems so we recommend to stick with 3.2.17 for now. We may update that if/when there’s a new GLoBES release.
