### ISSUE TITLE
Set "eos" argument for Garching models

### ISSUE THREAD

**Issue by soso128** [SNEWS2/snewpy#164]
Hi,

I noticed there is a keyword argument in the constructor of the GarchingArchiveModel class to set the EOS. Is there a way to set the value of this argument when calling the generate_time_series function of snowglobes.py? I didn't see any **kwargs option.

Best regards,
Sonia

**Comment by JostMigenda** [comment]
Hi Sonia! Thus far, all data files corresponding to the `_GarchingArchiveModel` class (i.e. `Bollig_2016`, `Tamborra_2014`, `Walk_2018` and `Walk_2019`) use the LS220 EOS, so unless I’m missing something, it shouldn’t be necessary to manually set that argument? But you’re right; if we add model files in that format with a different EOS at some point, we’ll need to make some changes.

**Comment by soso128** [comment]
Hi Jost, 
Yes indeed I was wondering about how to change the EOS if we want to try a different model in this class. But I guess I can just add a **kwargs in generate_time_series and use it when calling the constructor.

**Comment by JostMigenda** [comment]
Ah, I see—yes, that sounds like a good solution! Once you’ve done that, could you please create a PR so everyone can benefit from this?

**Comment by JostMigenda** [comment]
After thinking about it some more, I realized that this also affects the `OConnor_2013` model, which has a keyword argument for the progenitor mass. Right now, `generate_time_series()` cannot pass that argument, so users can only use the default mass with `snewpy.snowglobes`. So this issue also affects users who don’t use custom models and I’ll mark it as a bug.

**Comment by soso128** [comment]
Hi, sorry for my late reply. I have opened a pull request with a possible fix.
