### ISSUE TITLE
Typo: Warren equation of state should be 'SFHo' not 'LS220'.

### ISSUE THREAD

**Issue by joesmolsky** [SNEWS2/snewpy#186]
In the definition of the Warren_2020 class, the variable 'eos' is set to 'LS220' by default.  

The link in the documentation (https://doi.org/10.5281/zenodo.3667908) and the paper (https://arxiv.org/pdf/1912.03328.pdf) indicate the equation of state used is 'SFHo'.

**Comment by sybenzvi** [comment]
@joesmolsky, good catch. Do you mind changing this and making a PR?

**Comment by joesmolsky** [comment]
Pull request submitted and pending review.

**Comment by sybenzvi** [comment]
Closed in PR #187.
