### ISSUE TITLE
Use same requirements in all SNEWS tools: SNEWPY, snewps-pt, snews-cs, snewpdag

### ISSUE THREAD

**Issue by mcolomermolla** [SNEWS2/snewpy#199]
As an example, now:
snews-pt 1.0.2.dev4 requires pandas~=1.4.2, while SNEWPY requires pandas 1.3.4, which is incompatible.

**Comment by JostMigenda** [comment]
@Sheshuk, you added the `pandas==1.3.4` requirement in https://github.com/SNEWS2/snewpy/commit/d126da84a4fb1d79ee1ff6da0f124feb32c5ece2#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552—was there any reason for this strict requirement or can we relax that?

**Comment by Sheshuk** [comment]
Sorry, missed this question. There is no reason for strict requirement, we can replace = to >=1.3.4 or just remove the version. 1.3.4 was the version I used at that moment, in principle there are no restrictions.
