### ISSUE TITLE
direction dependent luminosity of Tamborra 2014, 27 M_solar model duplicate in version 1.4b1

### ISSUE THREAD

**Issue by jakob2508** [SNEWS2/snewpy#261]
In SNEWPY version 1.4b1 the luminosity of the Tamborra 2014, 27 M_solar model in direction 1 and 2 for all flavors is the same. 

I modified the [example notebook](https://github.com/SNEWS2/snewpy/blob/main/models/Tamborra_2014/Tamborra_2014.ipynb) and plotted all flavours individually and show that direction 1 and 2 are overlapping.

Here is the minimal code:
```
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

from astropy import units as u 

from snewpy.neutrino import Flavor
from snewpy.models.ccsn import Tamborra_2014

mpl.rc('font', size=16)
%matplotlib inline


m27_1 = Tamborra_2014(progenitor_mass=27*u.solMass, direction=1)
m27_2 = Tamborra_2014(progenitor_mass=27*u.solMass, direction=2)
m27_3 = Tamborra_2014(progenitor_mass=27*u.solMass, direction=3)

fig, axs = plt.subplots(2, 2, figsize = (10,10),tight_layout=True)
ax = axs.ravel()
for j, flavor in enumerate(Flavor):
    for i, model in enumerate([m27_1, m27_2, m27_3]):
        ax[j].plot(model.time, model.luminosity[flavor]/1e51,  # Report luminosity in units foe/s
                    label='dir = {}'.format(i+1),
                    lw=2,
                    ls='--' if i == 1 else '-')
    ax[j].set(xlim=(0.0, 0.35),
              ylim=(0.0, 75.0),
              xlabel=r'$t-t_{\rm bounce}$ [s]',
              ylabel=r'luminosity [foe s$^{-1}$]',
              title=r'{}: {} $M_\odot$, {}'.format(model.metadata['EOS'], model.metadata['Progenitor mass'].value, flavor.to_tex()))
    ax[j].grid()
    ax[j].legend(loc='lower center', ncol=2, fontsize=15)
```

This is the plot which shows that direction 1 (full blue line) and direction 2 (dashed orange line) overlay.
![image](https://github.com/SNEWS2/snewpy/assets/70433815/75d7b3ff-063f-46b9-9a37-4b89f1f035a2)

**Comment by JostMigenda** [comment]
Hi @jakob2508, thanks for reporting this and providing good sample code!

When running this sample code in a new notebook, however, I’m unable to reproduce the issue. I get the following figure instead, where all three direction have clearly distinct luminosities:
![image](https://github.com/SNEWS2/snewpy/assets/16189747/c7afdb2b-a39c-447f-8712-3f9851bb0340)

Could you try to delete the `Tamborra_2014` directory from the snewpy cache and rerun the code? That will redownload the data files, to exclude any issues related to local caches. You can find the snewpy cache directory by running
```Python
from snewpy import model_path
print(model_path)
# should return something like ~/.astropy/cache/snewpy/models
```

**Comment by JostMigenda** [comment]
Glad to hear that. Have a good weekend and let us know if you have any other feedback or issues in the future!
