### ISSUE TITLE
Liquid Scintillator

### ISSUE THREAD

**Issue by evanoconnor** [SNEWS2/snewpy#32]
I noticed liquid scintillator is not working with SNEWPY.  But it is not clear why (to me).  

> supernova.glb:135: error: Unknown name: #nue_e_signal
> 0 out/Bollig_2016_s11.2c_summed_AdiabaticMSW_NMO_ibd_scint20kt_events_unweighted.dat
> bin/supernova: ERROR: Experiment index 0 out of range.
> bin/supernova: ERROR: Error in glbGetChannelRates: 4th argument is larger than glb_num_of_exps.
> bin/supernova: ERROR: Error in glbGetUserData: 5th argument is larger than glb_num_of_exps.
> bin/supernova: ERROR: Error in glbGetUserData: 5th argument is larger than glb_num_of_exps.

**Comment by evanoconnor** [comment]
Ah, I see.  it crashes because no efficiency files exist and the .glb file is slightly misformatted. I will commit a fix

**Comment by JostMigenda** [comment]
@evanoconnor noted in #33 that this was fixed; so I suspect we can close this issue?

**Comment by JostMigenda** [comment]
I’ve tested `SNEWS2.0_rate_table_singleexample.py` with the `scint20kt` geometry and verified that it works; so this is indeed fixed.
