### ISSUE TITLE
possible error in `Odrzywolek_2010` model

### ISSUE THREAD

**Issue by JostMigenda** [SNEWS2/snewpy#321]
_(I’m moving this discussion from Slack over into an issue here, so we can keep track of this more easily.)_

We currently have an unexplained discrepancy between the `Odrzywolek_2010` preSN model in SNEWPY and Fig. 1 in the [recent SK preSN paper](https://arxiv.org/pdf/2205.09881). Both agree reasonably well for the Patton model, so the discrepancy is likely specific to the Odrzywolek model.

I was able to review the script to generate the SK figure and the main difference I see is in the normalization of the `nu_x` flux.
SNEWPY [currently uses a factor of 0.36](https://github.com/SNEWS2/snewpy/blob/1e1f520a7ee6a3c3c4240e87f1f55f9d7172e2ef/python/snewpy/models/presn_loaders.py#L58), which presumably comes from the 36.3% from Table 3 in [an earlier Odrzywolek _et al._ paper](https://arxiv.org/pdf/astro-ph/0311012)? In contrast, the SK paper appears to use 0.19; as does [an earlier KamLAND paper](https://arxiv.org/pdf/1506.01175) (just below equation 3).

If I understand correctly, Odrzywolek’s Table 3 says that the 36.3% are the fraction of the total (neutrino _plus_ anti-neutrino) emission that is ν_e. That means ν_μ and ν_τ each contribute 6.85%, to bring the total to 50% (plus another 50% from antineutrinos¹). Then the flux ratio of ν_x to ν_e would be 6.85/36.3≈0.19, i.e., exactly the number used by SK and KamLAND.
So I think that the 0.19 is actually correct and we currently have a bug. @Sheshuk, as our preSN expert, can you double-check?

¹ The paper takes into account pair production only, so for each flavour, the number of neutrinos will be equal to the number of antineutrinos.

**Comment by Sheshuk** [comment]
@JostMigenda, you're absolutely right, this looks like a mistake I made at initial implementation. @jpkneller also asked me about this factor earlier, and I couldn't remember and check where exactly did I get its.
Thanks a lot for your work!
We need to fix this factor
