### ISSUE TITLE
testing programs failing

### ISSUE THREAD

**Issue by joesmolsky** [SNEWS2/snewpy#40]
I think there is a file path issue in test_models.py.  I was getting this error:

_FileNotFoundError: [Errno 2] No such file or directory: 'models/Nakazato_2013/nakazato-shen-z0.004-t_rev100ms-s13.0.fits'_

It seems to be fixed by this:

_# mfile = 'models/Nakazato_2013/nakazato-shen-z0.004-t_rev100ms-s13.0.fits'
 mfile = '../../../models/Nakazato_2013/nakazato-shen-z0.004-t_rev100ms-s13.0.fits'_

However, test_models.py then returns this error:

_>       assert(np.interp(t.to(tunit), model.time, model.meanE[Flavor.NU_E])*Eunit == 6.79147181061522*u.MeV)
E       assert (<Quantity 6.79147181 MeV> * Unit("MeV")) == (6.79147181061522 * Unit("MeV"))
E        +  where <Quantity 6.79147181 MeV> = <function interp at 0x113c07820>(<Quantity -0.05 s>, <Quantity [-5.00e-02, -4.50e-02, -4.00e-02, -3.50e-02, -3.00e-02,\n           -2.50e-02, -2.00e-02, -1.50e-02, -1.00e-0...0e+01,  1.65e+01,  1.70e+01,\n            1.75e+01,  1.80e+01,  1.85e+01,  1.90e+01,  1.95e+01,\n            2.00e+01] s>, <Quantity [ 6.79147181,  6.57520706,  6.37220991,  6.24531325,  6.17775844,\n            6.17237819,  6.26160945,  6.48...,  6.59359318,\n            6.55147677,  6.51105652,  6.47423821,  6.43375075,  6.39386982,\n            6.35483985] MeV>)
E        +    where <function interp at 0x113c07820> = np.interp
E        +    and   <Quantity -0.05 s> = <bound method Quantity.to of <Quantity -50. ms>>(Unit("s"))
E        +      where <bound method Quantity.to of <Quantity -50. ms>> = <Quantity -50. ms>.to
E        +    and   <Quantity [-5.00e-02, -4.50e-02, -4.00e-02, -3.50e-02, -3.00e-02,\n           -2.50e-02, -2.00e-02, -1.50e-02, -1.00e-0...0e+01,  1.65e+01,  1.70e+01,\n            1.75e+01,  1.80e+01,  1.85e+01,  1.90e+01,  1.95e+01,\n            2.00e+01] s> = Nakazato_2013 Model: nakazato-shen-z0.004-t_rev100ms-s13.0.fits\nProgenitor mass : 13.0 solMass\nMetallicity     : 0.004\nRevival time    : 100.0 ms\nEq. of state    : SHEN.time
E        +  and   Unit("MeV") = u.MeV

test_models.py:30: AssertionError_

Running test_xforms.py returned the following error:

_ImportError: cannot import name 'NonAdiabaticMSW' from 'snewpy.flavor_transformation'_

I think there is a typo in flavor_transform.py. There seems to be an extra 'H' in the class definition I made the following change and this test was passed.

_# class NonAdiabaticMSWH(FlavorTransformation):
class NonAdiabaticMSW(FlavorTransformation):_

That passes the nonadiabatic test.  I now get an error with the 2 flavor decoherence test:

_>       assert(xform.prob_ee(t, E) == 0.5)
E       assert <Quantity 0.15956689> == 0.5
E        +  where <Quantity 0.15956689> = <bound method TwoFlavorDecoherence.prob_ee of <snewpy.flavor_transformation.TwoFlavorDecoherence object at 0x119f45670>>(<Quantity [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.] s>, <Quantity [  1.  ,   5.95,  10.9 ,  15.85,  20.8 ,  25.75,  30.7 ,  35.65,\n            40.6 ,  45.55,  50.5 ,  55.45,  60.4 ,  65.35,  70.3 ,  75.25,\n            80.2 ,  85.15,  90.1 ,  95.05, 100.  ] MeV>)
E        +    where <bound method TwoFlavorDecoherence.prob_ee of <snewpy.flavor_transformation.TwoFlavorDecoherence object at 0x119f45670>> = <snewpy.flavor_transformation.TwoFlavorDecoherence object at 0x119f45670>.prob_ee

test_xforms.py:170: AssertionError_

**Comment by JostMigenda** [comment]
Regarding the file path issue: I think this is relative to your current working directory. So if you’re in `python/snewpy/tests/` then you need to back-pedal in the file path; but you can simply run `pytest` from the root directory of the repo and then it runs just fine. (That’s also what we do in `.github/workflows/test.yml`.)

I’ve fixed the ImportError in #43 (note that the H in the class name is intentional, since there can be two MSW level crossings; one of which is commonly labeled H) and also discuss the remaining two AssertionErrors there.
