### ISSUE TITLE
Cleanup of {to,run,from}_snowglobes

### ISSUE THREAD

**Issue by JostMigenda** [SNEWS2/snewpy#82]
(This is not a big deal in the grand scheme of things, but we should make these changes before we publish the ApJ paper; afterwards, changing the API to be different from what’s described in the paper will lead to user confusion.)

* The main function of `run_snowglobes` should be called `run` instead of `go`. (It seems confusing to me to use different verbs in the function name and module name; and of the two, _run_ is preferable because you don’t _go_ SNOwGLoBES, you _run_ SNOwGLoBES.
* Having separate arguments for the folder containing the tarfile and the tarfile itself is unnecessary. This should just be one argument; if the components are ever needed separately, `os.path.split` can easily do that.
* The go/run function needs a brief docstring, to help with #76.

I’ll try to work on this early next week; just wanted to write it down already so we don’t forget.

**Comment by JostMigenda** [comment]
The second and third point apply equally to `to_snowglobes` and `from_snowglobes`.

**Comment by JostMigenda** [comment]
After discussing it with @jpkneller this afternoon, here’s a bigger proposal on the renaming: Combine all three modules into one module for all SNOwGLoBES interaction and rename `go` to either `run` (as suggested above) or `simulate`. The resulting code could look like this:
```
from snewpy.snowglobes import generate_fluence, simulate, collate

# do other imports and any setup here

print("Preparing fluences for SNOwGLoBES …")
tarfile = generate_fluence(…)

print("Running SNOwGLoBES …")
simulate(…)

print("Collating SNOwGLoBES outputs …")
tables = collate(…)
```

Since these three functions are closely related and almost always used together, it seems much cleaner to have them in one module rather than in three separate ones that each contain just a single function.
(I realise this proposal would mean a bit of work to update the code and notebooks, but I’d volunteer to do that.)

**Comment by JostMigenda** [comment]
For people who use custom scripts/notebooks to call these functions, we could leave a little stub under the old name which effectively acts as a redirect. That way, things would continue to work for legacy code, while new code could benefit from the cleaner API.

**Comment by sybenzvi** [comment]
Sounds good. I definitely support merging the modules.

**Comment by JostMigenda** [comment]
Great, thanks! I should be able to get to it this afternoon, after our regular meeting.
@evanoconnor, I think you’re the only main developer who hasn’t chimed in yet—please let me know if you see any major issues with this; otherwise we can discuss details once the PR is ready.
