### ISSUE TITLE
crash when collating outputs after using `generate_time_series`

### ISSUE THREAD

**Issue by JostMigenda** [SNEWS2/snewpy#90]
Found this as a result of debugging #55.
To reproduce: Run the sample code in `doc/nb/SNEWPY_examples.ipynb` but replace
```
tarredfile = to_snowglobes.generate_fluence(modeldir, filename, modeltype, transformation, distance, outfile,tstart,tend)
```
with
```
tarredfile = to_snowglobes.generate_time_series(modeldir, filename, modeltype, transformation, None, distance, outfile, None, None)
```

The result:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jost/Documents/Academia/SNEWS/Software/snowglobes//out//s17_nc_numu_O16_icecube_events_smeared_weighted.dat'
```
When adding the optional argument `remove_generated_files=False` to `generate_time_series()`, the result instead becomes:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jost/Documents/Academia/SNEWS/Software/snowglobes//fluxes/s17.dat'
```

I suspect this is because `generate_time_series()` adds multiple files with that name to the tarfile (one per time slice); so when `collate()` looks at the tarfile to build a list of files to clean up, it will add `fluxes/s17.dat` multiple times. The first attempt to delete it will suceed, but the second attempt will result in the FileNotFoundError.
(Key piece of evidence: If you [set `ntbins = 1`](https://github.com/SNEWS2/snewpy/blob/main/python/snewpy/to_snowglobes.py#L48), it will not crash.)

**Comment by evanoconnor** [comment]
Thanks for spotting this Jost, I heavily debugged the `generate_fluence()` part when introducing the file cleanup, but I guess not so much the `generate_time_series()`.
