### ISSUE TITLE
Kuroda_2020 notebook and model calls broken

### ISSUE THREAD

**Issue by sybenzvi** [SNEWS2/snewpy#97]
Access to data in `Kuroda_2020` models is broken. SNOwGLoBES code and documenting notebook are both affected. Fix ASAP!

**Comment by JostMigenda** [comment]
Partial fix in #95; and the notebook issue is already in #96. (Both should really go in ASAP, before submitting to JOSS!)

I think the next step would be to add basic tests for all models, to avoid repeating anything like this. I think that’s not quite as urgent, and we can leave this to the v1.2 milestone (as you did).
